// Builds shareable performance reports with zero dependencies.
// HTML: a self-contained file (inline CSS + inline SVG equity curve), printable to PDF.
// Markdown: a compact text summary for chat.
//
// stats is computed by the caller from scoped trades and passed in as:
// { rangeLabel, count, net, winRate, pf, expDollar, expR, maxDD, avgWin, avgLoss,
//   byStrategy: [{name, value}], equity: [number], generatedAt }

function esc(s) {
  return String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
}

function money(n, sign = false) {
  const v = Number(n) || 0
  const s = `$${Math.abs(v).toLocaleString('en-US', { maximumFractionDigits: 0 })}`
  if (v < 0) return `-${s}`
  return sign && v > 0 ? `+${s}` : s
}

// Tiny inline SVG line of the equity curve. No library.
function equitySvg(series, w = 720, h = 200) {
  if (!series || series.length < 2) return ''
  const min = Math.min(0, ...series)
  const max = Math.max(0, ...series)
  const span = max - min || 1
  const stepX = w / (series.length - 1)
  const y = (v) => h - ((v - min) / span) * h
  const pts = series.map((v, i) => `${(i * stepX).toFixed(1)},${y(v).toFixed(1)}`).join(' ')
  const zeroY = y(0).toFixed(1)
  const last = series[series.length - 1]
  const stroke = last >= 0 ? '#1a9d57' : '#d23f3f'
  return `<svg viewBox="0 0 ${w} ${h}" width="100%" preserveAspectRatio="none" style="display:block">
    <line x1="0" y1="${zeroY}" x2="${w}" y2="${zeroY}" stroke="#ccc" stroke-dasharray="4 4"/>
    <polyline fill="none" stroke="${stroke}" stroke-width="2.5" points="${pts}"/>
  </svg>`
}

export function buildReportHTML(stats) {
  const rows = (stats.byStrategy || [])
    .map((s) => `<tr><td>${esc(s.name)}</td><td style="text-align:right;color:${s.value >= 0 ? '#1a9d57' : '#d23f3f'}">${money(s.value, true)}</td></tr>`)
    .join('')
  const stat = (label, value, pos) =>
    `<div class="s"><div class="sl">${esc(label)}</div><div class="sv" style="color:${pos == null ? '#111' : pos ? '#1a9d57' : '#d23f3f'}">${esc(value)}</div></div>`

  return `<!doctype html><html><head><meta charset="utf-8"><title>P n Ledger report — ${esc(stats.rangeLabel)}</title>
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#111;max-width:840px;margin:32px auto;padding:0 20px;line-height:1.5}
  h1{font-size:22px;margin:0 0 2px} .sub{color:#777;font-size:13px;margin-bottom:20px}
  .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin:18px 0}
  .s{border:1px solid #e6e6e6;border-radius:10px;padding:10px 12px}
  .sl{font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:#888}
  .sv{font-size:19px;font-weight:700;font-variant-numeric:tabular-nums;margin-top:3px}
  .card{border:1px solid #e6e6e6;border-radius:12px;padding:16px;margin:16px 0}
  .ct{font-size:13px;font-weight:600;color:#444;margin-bottom:10px}
  table{width:100%;border-collapse:collapse;font-size:13px}
  td{padding:6px 4px;border-bottom:1px solid #f0f0f0;font-variant-numeric:tabular-nums}
  .foot{color:#aaa;font-size:11px;margin-top:24px}
  @media print{body{margin:0}.card,.s{break-inside:avoid}}
</style></head><body>
  <h1>P n Ledger — performance report</h1>
  <div class="sub">${esc(stats.rangeLabel)} · ${stats.count} trades · generated ${esc(stats.generatedAt)}</div>
  <div class="grid">
    ${stat('Net P/L', money(stats.net, true), stats.net >= 0)}
    ${stat('Win rate', `${Math.round(stats.winRate)}%`, null)}
    ${stat('Profit factor', stats.pf === Infinity ? '∞' : stats.pf.toFixed(2), stats.pf >= 1)}
    ${stat('Expectancy', money(stats.expDollar, true), stats.expDollar >= 0)}
    ${stat('Expectancy (R)', stats.expR == null ? '—' : `${stats.expR >= 0 ? '+' : ''}${stats.expR.toFixed(2)}R`, stats.expR == null ? null : stats.expR >= 0)}
    ${stat('Max drawdown', money(-stats.maxDD), false)}
    ${stat('Avg win', money(stats.avgWin), true)}
    ${stat('Avg loss', money(-stats.avgLoss), false)}
  </div>
  <div class="card"><div class="ct">Equity curve (cumulative net P/L)</div>${equitySvg(stats.equity)}</div>
  ${rows ? `<div class="card"><div class="ct">P/L by strategy</div><table><tbody>${rows}</tbody></table></div>` : ''}
  <div class="foot">Generated by P n Ledger. Performance figures only — no account identifiers or personal data included.</div>
</body></html>`
}

export function buildReportMarkdown(stats) {
  const lines = [
    `# P n Ledger — ${stats.rangeLabel}`,
    `*${stats.count} trades · generated ${stats.generatedAt}*`,
    '',
    `- **Net P/L:** ${money(stats.net, true)}`,
    `- **Win rate:** ${Math.round(stats.winRate)}%`,
    `- **Profit factor:** ${stats.pf === Infinity ? '∞' : stats.pf.toFixed(2)}`,
    `- **Expectancy:** ${money(stats.expDollar, true)} / trade`,
    `- **Expectancy (R):** ${stats.expR == null ? '—' : `${stats.expR >= 0 ? '+' : ''}${stats.expR.toFixed(2)}R`}`,
    `- **Max drawdown:** ${money(-stats.maxDD)}`,
    `- **Avg win / loss:** ${money(stats.avgWin)} / ${money(-stats.avgLoss)}`,
  ]
  if (stats.byStrategy?.length) {
    lines.push('', '## By strategy')
    stats.byStrategy.forEach((s) => lines.push(`- ${s.name}: ${money(s.value, true)}`))
  }
  return lines.join('\n')
}
